blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('<int:pid>' ,blog_single, name='single'),
    path('category/<str:cat_name>' ,blog_category, name='category'),
    path('author/<str:author_username>' ,blog_view, name='author'),
    path('search/',blog_search,name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('',include('website.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index_view, name='index'),
    path('about',about_view, name = 'about'),
    path('contact',contact_view, name = 'contact')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
     name = models.CharField(max_length=255)
     def __str__(self):
          return self.name
    
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title =  models.CharField(max_length=255)
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    content = models.TextField()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name  

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger


# Create your views here.
def blog_view(request,**kwargs):
    now = timezone.now()
    posts = Post.objects.filter(status=1,published_date__lte=now)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name = kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    posts = Paginator(posts,2)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts=posts.get_page(1)
    except EmptyPage:
        posts=posts.get_page(1)
    context = {'posts' : posts}
    return render(request,'blog/blog-home.html',context)



def blog_single(request,pid):
    now = timezone.now()
    post = get_object_or_404(Post,pk=pid,status=1,published_date__lte=now)
    post.counted_views += 1 
    post.save()
    context = {'post':post}
    return render(request,'blog/blog-single.html',context)

def blog_category(request,cat_name):
    now = timezone.now()
    #posts = get_object_or_404(Post,status=1,published_date__lte=now)
    posts = Post.objects.filter(status=1,published_date__lte=now)
    posts = posts.filter(category__name=cat_name)
    context = {'posts':posts}
    return render(request,'blog/blog-home.html',context)

def blog_search(request):
    now = timezone.now()
    #posts = get_object_or_404(Post,status=1,published_date__lte=now)
    posts = Post.objects.filter(status=1,published_date__lte=now)
    if request.method == 'GET':
        if s:= request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {'posts':posts}
    return render(request,'blog/blog-home.html',context)

website/views.py
from django.shortcuts import render

# Create your views here.
def index_view(request):
    return render(request,'website/index.html')

def about_view(request):
    return render(request,'website/about.html')

def contact_view(request):
    return render(request,'website/contact.html')
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png'}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul>
                            <li><a href="#">Visit Us</a></li>
                            <li><a href="#">Buy Tickets</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                        <div class="header-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png'}" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'website:index'%}">Home</a></li>
                        <li><a href="{% url  'website:about' %}">About</a></li>
                        <li><a href="{% url 'blog:index' %}">Blog</a></li>
                        <li><a href="{% url  'website:contact' %}">Contact</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->

    {% block content %}

    {% endblock %}

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">

            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message. It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div id="mc_embed_signup">
                            <form target="_blank"
                                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                method="get" class="subscription relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>{% if not forloop.last %},{% endif %}
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' pid=post.id %}">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
							{{post.content|truncatewords:2}}
						</p>
						<a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">
						{% if posts.has_previous %}
						<li class="page-item">
							<a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
						</li>
						{% endif %}
						{% for i in posts.paginator.page_range %}
						{% if posts.number == i %}
						<li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
						{% else %}
						<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
						{% endif %}
						{% endfor %}

						{% if posts.has_next %}
							<li class="page-item">
							    <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
								    <span aria-hidden="true">
									    <span class="lnr lnr-chevron-right"></span>
								    </span>
							    </a>
						    </li>
						{% endif %}
					</ul>
				</nav>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% postcategories %}
					{% latestposts %}
					{% include 'blog/blog-ads.html' %}

					{% include 'blog/blog-newsletter.html'%}
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{ post.published_date|date:"d M Y"}}</p>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

templates/blog/blog-post-categories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> {{post.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="#">{{cat.name}}</a></li>{% if not forloop.last %},{% endif %}
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_views }} Views</a>
								<span class="lnr lnr-eye"></span>
							</p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.content}}
						</p>

					</div>

				</div>
				
				<div class="navigation-area">
					<div class="row">
                        {% prev_post post.id %}
						{% next_post post.id %}
					</div>
					
				</div>
				
				<div class="comments-area">
					<h4>05 Comments</h4>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Emilly Blunt</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c2.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Elsie Cunningham</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c3.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Annie Stephens</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c4.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Maria Luna</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c5.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Ina Hayes</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form>
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" id="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" id="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						<div class="form-group">
							<input type="text" class="form-control" id="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<a href="#" class="primary-btn text-uppercase">Post Comment</a>
					</form>
				</div>
			</div>
			
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% include 'blog/blog-post-categories.html' %}
					{% latestposts %}
					{% include 'blog/blog-ads.html'%}

					{% include 'blog/blog-newsletter.html' %}
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}